#!/bin/sh

if [[ -z $DOT_REPO ]]; then
	DOT_REPO=$HOME/dotfiles
fi

if [[ -z $DOT_TARGET_DIR ]]; then
	DOT_TARGET_DIR=$HOME/.local/bin
fi

echo "Installing $DOT_REPO/dot to $DOT_TARGET_DIR"

if [ ! -d $DOT_TARGET_DIR ]; then
	mkdir -pv $DOT_TARGET_DIR
fi

ln -sfv $DOT_REPO/dot $DOT_TARGET_DIR/dot

echo "Done."
echo "Please add $DOT_TARGET_DIR to \$PATH."
echo "Please set environment variable \$DOT_REPO in your profile. (Default is \$HOME/dotfiles)"

echo ""
echo "Updating dotfiles..."
$DOT_TARGET_DIR/dot all

echo "Installation finishes."
