icons_format = "{icon}"

[theme]
theme = "ctp-macchiato"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_width:30) | i3 - FrozenArcher"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "backlight"
minimum = 15
maximum = 100
cycle = [100, 50, 0, 50]

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT1"
format = "{percentage}"
full_format = "{percentage}"
hide_missing = true

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %Y-%m-%d %R') "
[block.theme_overrides]
idle_bg = { link = "info_bg" }
idle_fg = { link = "info_fg" }
